### ISSUE TITLE
Edit README based on 6/26 commit

### ISSUE THREAD

**Issue by fisherds** [GoogleCloudPlatform/appengine-endpoints-tictactoe-python#9]
(very minor)
The README still says to edit base.js to add the CLIENT_ID there, however, the 6/26 change:  https://github.com/GoogleCloudPlatform/appengine-endpoints-tictactoe-python/commit/bd210e9a611665fc4567de63bb476798f202499c

Moved the client id into the render.js file.  Just change the text base.js in the README to render.js.

**Comment by dhermes** [comment]
Thanks @fisherds!
